apiVersion: v1
kind: Secret
metadata:
  name: judgex-secret
  namespace: {{ include "judgex.namespace" . }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.config.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.config.secrets.jwtSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.config.secrets.adminPassword | quote }}
  LLM_API_KEY: {{ .Values.config.secrets.llmApiKey | quote }}
  MINIO_ACCESS_KEY: {{ .Values.config.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.config.secrets.minioSecretKey | quote }}
